#!/usr/bin/env bash

xhost +local:docker &>/dev/null

docker run \
  --rm=true \
  --shm-size=256m \
  --device /dev/snd \
  --device /dev/video0 \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  --volume /etc/localtime:/etc/localtime:ro \
  --env uid="$(id -u)" \
  --env gid="$(id -g)" \
  --env DISPLAY="unix$DISPLAY" \
  --name chromium \
  local/chromium \
  "--no-sandbox" \
  "--disable-setuid-sandbox" \
  &
